#### Software options ####

# For QIIME and Amptk, it is possible to configure the
# Conda environment, where the software is installed,
# allowing to switch between different versions.
# Note: qiime or amptk entries can be missing if clustering/
#  taxonomy assignment methods from these pipelines are
#  not used in the pipelines definition below.
software:
  qiime:
    conda_env: qiime2-2022.8
  amptk:
    conda_env: amptk


#### Input files ####

input:
  # Lists of directories and/or glob patterns can be specified.
  # There is no problem if some files are matched by both, they will only
  # be included once.
  directories:
    - test/gz
  patterns:
    - path/to/other/files/**/Abc*.gz
  # recursive: true causes directories to be searched recursively, and
  # glob patterns can contain /**/ to match unknown/unlimited directory depth
  # (like the globstar option in Bash)
  recursive: true
  # Multiple files with the same name in different directories are
  # either pooled together before processing (if pool_duplicates is true)
  # or a suffix number (_1, _2, etc.) is added to make the sample names
  # unique (if pool_duplicates is false).
  # Which samples were pooled is listed in 'results/samples.yaml' after
  # running the 'config' or other commands.
  pool_duplicates: false
  # The name pattern is an important setting that should be correctly
  # specified.
  # While no metadata file specifying sample names and corresponding input files
  # is required (such as with QIIME), it is necessary to specify the correct 
  # name pattern to obtain sample names from the file names.
  # Options are:
  # - sample_read: e.g. Sample_Name_R1.fastq.gz
  # - illumina: e.g. Sample_Name_S276_L001_R1_001.fastq.gz
  # - regular expression with two groups, the first one matches the sample name
  #     and the second one the read number (1 = forward, 2 = reverse).
  #     For example, the sample_read pattern looks like this:
  #     '(.+?)_R([12])\.fastq\.gz'
  #     The illumina pattern: "(.+?)_S\d+_L\d+_R([12])_\d{3}\.fastq\.gz"
  name_pattern: sample_read  # {sample_read, illumina, <regex>}

##### Pipeline definition ####

# Each pipeline needs two options:
#  cluster: name of a clustering/denoising method
#  taxonomy: either 'default' (all databases and methods listed
#    below under the 'taxonomy_dbs' and 'taxonomy_methods' options,
#    or a custom combination of database/method names
#     (see example in 'unoise_usearch' pipeline)
pipelines:
  # UNOISE3 pipeline using VSEARCH for denoising
  unoise:
    cluster: usearch_unoise3  # { usearch_unoise3, qiime_dada2, amptk_unoise3, amptk_dada2 }
    taxonomy: default # using all taxonomy_dbs and taxonomy_methods
  # UNOISE3 pipeline using USEARCH for denoising and a custom combination
  # of taxonomy databases/assignment methods
  unoise_usearch:
    cluster: usearch_unoise3  # { usearch_unoise3, qiime_dada2, amptk_unoise3, amptk_dada2 }
    taxonomy:
      dbs:  # chooses specific 'taxonomy_dbs' (below)
        ITS: [unite_species]
      methods:  # chooses specific 'taxonomy_methods' (below)
        - sintax_90
    # Here, we choose USEARCH for denoising instead of VSEARCH.
    # These settings simply overwrite the default settings found below
    # in this file. 
    # The settings hierarchy needs to be exactly the same as below,
    # if not the options here will be ignored. It is recommended to
    # run the 'config' rule first and then check the file 
    # `results/<pipeline>/config.yaml` to see if the settings were 
    # correctly overridden.
    settings:
      usearch:
        unoise: { program: usearch }
  # QIIME / DADA2
  qiime_dada2:
    cluster: qiime_dada2  # { usearch_unoise3, qiime_dada2, amptk_unoise3, amptk_dada2 }
    taxonomy: default
  # Amptk with UNOISE3 clustering
  amptk_unoise:
    cluster: amptk_unoise3
    taxonomy: default
  # Amptk with Dada2 clustering
  amptk_dada2:
    cluster: amptk_dada2
    taxonomy: default

#### Files to compare with ASVs/OTUs using usearch_global (VSEARCH) ####

compare:
  my_comparison:
    file: path/to/seqs.fasta  # searched against denoised.fasta
    ident_threshold: 0.8  # min. identity (0 - 1)
    maxhits: 1
  default_settings:
    ident_threshold: 0.9
    maxhits: 1
    maxaccepts: 64
    maxrejects: 64

#### Primers ####

primers:
  # Primers are grouped per marker. The marker name (in this case ITS) needs to be
  # present in the 'taxonomy_dbs' configuration. Only databases from the given
  # marker will be used for taxonomy assignments.
  # Furthermore, some marker-specific rules such as 'ITSx' will only be run with ITS sequences
  ITS:
    # Several primers can be specified. The desired combinations can be
    # specified as well (see 'combinations' below. Multiple primer combinations
    # may occur if:
    # - Different samples were amplified with different primers
    # - Some or all samples are a mix of different amplicons, which were pooled before indexing
    # Each primer can further be a comma delimited list of oligos, which
    # were mixed together. However, they should still start at the same
    # nucleotide position to allow global trimming. Note that some pipelines
    # cannot deal with primer mixtures, in these cases the consensus sequence of the
    # single mixed sequences is used.
    # The oligos may include adapter and/or linker sequences, but their position is not
    # required to be at the exact sequence start or end.
    forward:
      - ITS3-KYO2: GGGATGAAGAACGYAGYRAA
      # - fITS7: GTGARTCATCGAATCTTTG
    reverse:
      - ITS4: AATCCTCCGCTTATTGATATGC,AATCCTCCGCTGAWTAATATGC
    # Primer combinations: either 'default' (to use all possible combinations),
    #   or a list of combinations (see below)
    combinations: default
      ## Instead of 'default', a list of specific desired combinations
      ## can be supplied. Every combination will obtain its own results directory
      ## (named "marker__forward...reverse")
      ## The primer combination format must be: "forward...reverse"
      # - ITS3-KYO2...ITS4
      # - fITS7...ITS4
  # Primer trimming settings
  trim_settings:
    min_overlap: 15
    max_error_rate: 0.25

#### Taxonomy assignment ####

# By default, every possible combination of databases and
# assignment methods is used. This can be changed by modifying
# the 'taxonomy' option in the 'pipelines' definion (above)

# Definition of all taxonomic databases used by default
# (sources are configured in taxonomy.yaml).
# Optional filters allow to only keep reference sequences
# with a certain taxonomic rank defined.
# TODO: More filtering or trimming options could be added
taxonomy_dbs:
  ITS:
    # UNITE including global and 97% singletons (doi.org/10.15156/BIO/1264861)
    unite:
      db: unite_eukarya_all  # defined in taxonomy.yaml
    unite_species:
      db: unite_eukarya_all  # defined in taxonomy.yaml
      # only keep references with known species annotation
      defined: species
  COI:
    midori:
      db: Midori_COI
  Mito_16S:
    midori:
      db: Midori_16S

# Assignment methods
taxonomy_methods:
  # SINTAX (USEARCH)
  sintax_90:
    method: sintax_usearch  # { sintax_usearch, qiime_sklearn }
    confidence: 0.9
    program: vsearch
  sklearn_90:
    # classify-sklearn plugin in QIIME2 with Naive Bayes classifier
    # note: the creation of the database and the taxonomy assignment use
    #   a lot of memory with the UNITE database.
    method: qiime_sklearn  # { sintax_usearch, qiime_sklearn }
    confidence: 0.9

#### Default settings ####

# All of these settings can be overridden by individual pipelines
# using the 'settings' key (see 'pipelines' above)

# General filter settings
filter:
  min_length: 100

# Usearch pipeline specific settings
usearch:
  # paired end merging (currently done by USEARCH)
  # TODO: should be configurable
  merge:
    overlap_ident: 75  # percent
    # max. nucleotide differences
    # by default, we don't care about this, only rely on overlap identity
    max_diffs: 1000
    # How long is the merged amplicon expected on average?
    # Only used to calculate expected errors for pipelines not accepting
    # error rates for quality filtering (only absolute number of expected errors)
    expected_length: 400

  # read filtering before denoising
  # (done by VSEARCH)
  filter:
    # Maximum per-base error rate
    # (e.g. 0.002 per bp means 0.8 errors per 400 bp)
    max_error_rate: 0.002

  # UNOISE3 options
  unoise:
    min_size: 8
    program: vsearch  # { vsearch, usearch }

  # mapping options for creation of OTU table
  # (done by VSEARCH)
  otutab:
    maxaccepts: 64
    maxrejects: 64
    ident_threshold: 0.98

# DADA2 specific settings
dada2:
  trim_max_err: 1.0
  max_err_fwd: 1
  max_err_rev: 15
  trunc_fwd: 280
  trunc_rev: 250
  chimera_method: consensus  # { consensus, per-sample, pooled }
  pooling_method: independent  # { independent, pseudo, pooled }
  merge_maxdiffs: 1

# ITS recognition (fungi)
# for options see https://microbiology.se/publ/itsx_users_guide.pdf
ITSx:
  # Taxonomic groups to include or "all" (which is the slowest
  # setting, but probably best as well unless you are sure that
  # there are only sequences from certain groups.
  organism_groups: all  # -t setting
  # Domain E-value cutoff in HMMER search for sequence to be included
  # in the output (ITSx default: 1.0e-5)
  # note: 1e-5 does not work, only 1.e-5 or 1.0e-5 (otherwise validator will fail)
  e-value: 1.0e-5
  #
  # All the following options are *optional*, we just show the defaults
  # here (sometimes different from ITSx defaults)
  allow_single_domain: 1e-9,0
  complement: F  # ITSx uses T (true) as default, but we know the orientation of our amplicon
  heuristics: F
  # common output options
  graphical: F  # ITSx has T as default
  fasta: T
  preserve: F
  save_regions: all  # ITSx has only ITS1,ITS2 as default
  partial: 50  # ITSx has 0 as default
